package br.com.tedeschi.safeunlock.persistence.vo;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table TB_CONNECTION.
 */
public class Connection {

    private Long id;
    /** Not-null value. */
    private String name;
    /** Not-null value. */
    private String uniqueId;
    private int type;
    private Boolean checked;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Connection() {
    }

    public Connection(Long id) {
        this.id = id;
    }

    public Connection(Long id, String name, String uniqueId, int type, Boolean checked) {
        this.id = id;
        this.name = name;
        this.uniqueId = uniqueId;
        this.type = type;
        this.checked = checked;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(String name) {
        this.name = name;
    }

    /** Not-null value. */
    public String getUniqueId() {
        return uniqueId;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUniqueId(String uniqueId) {
        this.uniqueId = uniqueId;
    }

    public int getType() {
        return type;
    }

    public void setType(int type) {
        this.type = type;
    }

    public Boolean getChecked() {
        return checked;
    }

    public void setChecked(Boolean checked) {
        this.checked = checked;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
